# Use SDK for build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy csproj and restore
COPY *.csproj ./
RUN dotnet restore
COPY . ./

# Publish
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet AS runtime

WORKDIR /app

# Copy the published output from the build stage
COPY --from=build /app/out ./

# Set environment variables
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_URLS=http://+:80

# Expose the port and set the entry point
EXPOSE 80
ENTRYPOINT ["dotnet", "mcpserver.dll"]